[package]
name = "a"
version = "0.1.0"
edition = "2021"
authors = ["daniel040607 <daniel0406070@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.3.14"

